name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: tommy351/gcloud-pubsub-emulator
      - name: Build and push (Alpine)
        uses: docker/build-push-action@v2
        with:
          context: alpine
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: tommy351/gcloud-pubsub-emulator:alpine
